# Generated by Django 3.1 on 2020-08-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20200823_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title_tag',
            new_name='img_tag',
        ),
        migrations.AlterModelTable(
            name='image',
            table='gallery_image',
        ),
    ]
